# Site settings
title: IMAGINE THE FLOOR.
description: つくば市のクラブ OctBaSS で定期的に開催されているイベント IMAGINE THE FLOOR. &#35;ITF_DJ の公式サイトです。
baseurl: ""
url: "https://imaginethefloor.tk"
twitter_username: ITF_DJ

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["strikethrough"]
exclude: ["vendor", "Gemfile", "Gemfile.lock", "Makefile", "CNAME"]
gems:
  - jekyll-redirect-from
