# Site settings
title: IMAGINE THE FLOOR.
description: つくば市のクラブ OctBaSS で定期的に開催されているイベント IMAGINE THE FLOOR. &#35;ITF_DJ の公式サイトです。
baseurl: ""
url: "https://imaginethefloor.tk"
twitter_username: ITF_DJ

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["strikethrough"]
exclude: ["vendor"]


events:
  archives:
    - name: vol.1
      short_name: 1
      date: 2014-03-30
      flyer: /images/flyers/vol_1.png
      archive: vol_1.html
    - name: vol.2
      short_name: 2
      date: 2014-06-15
      flyer: /images/flyers/vol_2.png
      archive: vol_2.html
    - name: vol.3
      short_name: 3
      date: 2014-09-28
      flyer: /images/flyers/vol_3.png
      archive: vol_3.html
    - name: vol.4
      short_name: 4
      date: 2014-12-07
      flyer: /images/flyers/vol_4.png
      archive: vol_4.html
    - name: IMAGINE THE PIZZA.
      short_name: P1
      date: 2015-01-16
      flyer: /images/flyers/itp_vol_1.jpg
      archive: itp_dj/vol_1.html
    - name: vol.5
      short_name: 5
      date: 2015-03-08
      flyer: /images/flyers/vol_5.png
      archive: vol_5.html
    - name: vol.6
      short_name: 6
      date: 2015-06-14
      flyer: /images/flyers/vol_6.png
      archive: vol_6.html
    - name: IMAGINE THE PIZZA. vol.2
      short_name: P2
      date: 2015-07-10
      flyer: /images/flyers/itp_vol_2.jpg
      archive: itp_dj/vol_2.html
    - name: vol.7
      short_name: 7
      date: 2015-09-27
      flyer: /images/flyers/vol_7.png
      archive: vol_7.html
    - name: vol.8
      short_name: 8
      date: 2016-01-17
      flyer: /images/flyers/vol_8.png
      archive: vol_8.html
  upcoming:
    name: vol.9
    short_name: 9
    date: 2016-04-17
    flyer: /images/flyers/vol_9.jpg
    url: http://twipla.jp/events/190969
